// <auto-generated />
using System;
using GerenciadorTarefas.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorTarefas.Infraestrutura.Persistencia.Migracoes
{
    [DbContext(typeof(ContextoBancoDados))]
    [Migration("20260312001420_AdicionarVinculosMultiplosProjeto")]
    partial class AdicionarVinculosMultiplosProjeto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<string>("Codigo")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("codigo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_codigo")
                        .HasFilter("codigo IS NOT NULL");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_areas_nome");

                    b.ToTable("areas", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Notificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("mensagem");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<bool>("Reatribuicao")
                        .HasColumnType("boolean")
                        .HasColumnName("reatribuicao");

                    b.Property<Guid>("ResponsavelUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_usuario_id");

                    b.Property<Guid>("TarefaId")
                        .HasColumnType("uuid")
                        .HasColumnName("tarefa_id");

                    b.Property<string>("TituloTarefa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo_tarefa");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao")
                        .HasDatabaseName("ix_notificacoes_data_criacao");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ResponsavelUsuarioId")
                        .HasDatabaseName("ix_notificacoes_responsavel_usuario_id");

                    b.HasIndex("TarefaId");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("GestorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("gestor_usuario_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_projetos_area_id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("GestorUsuarioId");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_projetos_nome");

                    b.ToTable("projetos", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.ProjetoArea", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.HasKey("ProjetoId", "AreaId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_projetos_areas_area_id");

                    b.ToTable("projetos_areas", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.ProjetoUsuarioVinculado", b =>
                {
                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("ProjetoId", "UsuarioId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_projetos_usuarios_vinculados_usuario_id");

                    b.ToTable("projetos_usuarios_vinculados", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_conclusao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataPrazo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_prazo");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("Prioridade")
                        .HasColumnType("integer")
                        .HasColumnName("prioridade");

                    b.Property<Guid>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("projeto_id");

                    b.Property<Guid>("ResponsavelUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_usuario_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("DataPrazo")
                        .HasDatabaseName("ix_tarefas_data_prazo");

                    b.HasIndex("ProjetoId")
                        .HasDatabaseName("ix_tarefas_projeto_id");

                    b.HasIndex("ResponsavelUsuarioId")
                        .HasDatabaseName("ix_tarefas_responsavel_usuario_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tarefas_status");

                    b.ToTable("tarefas", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<int>("PerfilGlobal")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_global");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("senha_hash");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acesso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.UsuarioArea", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid")
                        .HasColumnName("area_id");

                    b.HasKey("UsuarioId", "AreaId");

                    b.HasIndex("AreaId")
                        .HasDatabaseName("ix_usuarios_areas_area_id");

                    b.ToTable("usuarios_areas", (string)null);
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Notificacao", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_projetos_projeto_id");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "ResponsavelUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsavelUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_usuarios_responsavel_usuario_id");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Tarefa", "Tarefa")
                        .WithMany()
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_tarefas_tarefa_id");

                    b.Navigation("Projeto");

                    b.Navigation("ResponsavelUsuario");

                    b.Navigation("Tarefa");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Projeto", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_areas_area_id");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projetos_usuarios_criado_por");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "GestorUsuario")
                        .WithMany()
                        .HasForeignKey("GestorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_projetos_usuarios_gestor");

                    b.Navigation("Area");

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("GestorUsuario");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.ProjetoArea", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_areas_vinculo_area");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Projeto", "Projeto")
                        .WithMany("AreasVinculadas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_areas_vinculo_projeto");

                    b.Navigation("Area");

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.ProjetoUsuarioVinculado", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Projeto", "Projeto")
                        .WithMany("UsuariosVinculados")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_usuarios_vinculo_projeto");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projetos_usuarios_vinculo_usuario");

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Tarefa", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tarefas_projetos_projeto_id");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "ResponsavelUsuario")
                        .WithMany()
                        .HasForeignKey("ResponsavelUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tarefas_usuarios_responsavel_usuario_id");

                    b.Navigation("Projeto");

                    b.Navigation("ResponsavelUsuario");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.UsuarioArea", b =>
                {
                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Area", "Area")
                        .WithMany("UsuariosVinculados")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_areas_areas_area_id");

                    b.HasOne("GerenciadorTarefas.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("AreasVinculadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_areas_usuarios_usuario_id");

                    b.Navigation("Area");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Area", b =>
                {
                    b.Navigation("UsuariosVinculados");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Projeto", b =>
                {
                    b.Navigation("AreasVinculadas");

                    b.Navigation("UsuariosVinculados");
                });

            modelBuilder.Entity("GerenciadorTarefas.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("AreasVinculadas");
                });
#pragma warning restore 612, 618
        }
    }
}
