apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-api
  namespace: gerenciador-tarefas
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  BancoDados__AplicarMigracoesAutomaticamente: "true"
  BancoDados__AplicarSeedDadosDemonstracao: "false"
