apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gerenciador-tarefas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gustabrito/gerenciador-tarefas-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: configmap-api
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: segredo-banco-dados
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: segredo-banco-dados
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: segredo-banco-dados
                  key: POSTGRES_PASSWORD
            - name: ConnectionStrings__BancoDados
              value: Host=banco-dados;Port=5432;Database=$(POSTGRES_DB);Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)
